### ISSUE TITLE
How can I fit a 1.8 "160x128 screen?

### ISSUE THREAD

**Issue by caochangli123** [uraich/IoT-Course#1]

**Comment by uraich** [comment]
Sorry, I would need some more explanation which screen you want to connect to which device. 
If you have a WeMos D1 mini system and you want to use its standard interface then you may want to have a look at https://afnog.iotworkshop.africa/do/view/UCC_Course_2020/TFTDisplay
where I describe the displays I have. For the IoT course we are going to use the 120x128 pixel 1.4" display for which you can find the MicroPython driver in the modules folder of this repository

**Comment by caochangli123** [comment]
> Sorry, I would need some more explanation which screen you want to connect to which device.
> If you have a WeMos D1 mini system and you want to use its standard interface then you may want to have a look at https://afnog.iotworkshop.africa/do/view/UCC_Course_2020/TFTDisplay
> where I describe the displays I have. For the IoT course we are going to use the 120x128 pixel 1.4" display for which you can find the MicroPython driver in the modules folder of this repository

1.8" Color TFT LCD display with MicroSD Card Breakout - ST7735R. https://www.adafruit.com/product/358

**Comment by caochangli123** [comment]
> Sorry, I would need some more explanation which screen you want to connect to which device.
> If you have a WeMos D1 mini system and you want to use its standard interface then you may want to have a look at https://afnog.iotworkshop.africa/do/view/UCC_Course_2020/TFTDisplay
> where I describe the displays I have. For the IoT course we are going to use the 120x128 pixel 1.4" display for which you can find the MicroPython driver in the modules folder of this repository

How does ESP-WROOM-32 drive the 1.8-inch st7735 driver screen for full-screen display?

**Comment by caochangli123** [comment]
> Sorry, I would need some more explanation which screen you want to connect to which device.
> If you have a WeMos D1 mini system and you want to use its standard interface then you may want to have a look at https://afnog.iotworkshop.africa/do/view/UCC_Course_2020/TFTDisplay
> where I describe the displays I have. For the IoT course we are going to use the 120x128 pixel 1.4" display for which you can find the MicroPython driver in the modules folder of this repository

Sorry. After I checked your code carefully, I found that I asked a very stupid question. The following is my solution: st7735 =Display(spi,SPI_CS,SPI_DC,rst=21, width=128, height=160). So Easy. The above is translated using Google Translate. thank you for your sharing. An electronics enthusiast from China.
